### ISSUE TITLE
link to annotated source does not work

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-mem-store#18]
needs to display as static html - what is the easiest way to build/host this?
gh-pages a little awkward, but will do if nothing better

**Comment by mcdonnelldean** [comment]
@rjrodger I have a PR have ready to pull these to Senecajs.org automagically. Then each time the site is pulled the annotations will be regenerated and placed on the site ala senecajs.org/annotations/seneca.html

The name will match the plugin name.

**Comment by rjrodger** [comment]
great - i'd go ahead and make that live

**Comment by mcdonnelldean** [comment]
:+1: I need to finish it too but it will go out today.

**Comment by mcdonnelldean** [comment]
Annotations are now live at: http://senecajs.org/annotations/mem-store.html
