### ISSUE TITLE
stored entities keep references from originally input data 

### ISSUE THREAD

**Issue by psnider** [senecajs/seneca-mem-store#2]
I'm using seneca 0.6.5 for a micro-service that uses mongo.
In my plugin tests, I'm using seneca-mem-store (0.3.1, loaded by seneca).

I discovered that when I save an object, the object returned by **save$()** contains references to components of the originally input object.
I expect a new instance that shares no state with the original object.

This is causing side effects in my tests.
Here is a relevant code fragment:

```
this.make('person').save$(person, (error, created_person) => {
    // mark is not a field of person
    created_person['mark'] = 'yikes'
    console.log('AFTER MARKING person.mark=' + person['mark'])
    // contact_methods is a field of person that is an array with one element
    created_person.contact_methods.push('yikes')
    console.log('AFTER PUSH person.contact_methods=' + JSON.stringify(person.contact_methods))
}
```

This produces this console output:

```
AFTER MARKING person.mark=undefined
AFTER PUSH person.contact_methods=[{"method":"mobile","address":"(800) bob-smit"},"yikes"]
```

It appears that the seneca-mem-store is making a shallow copy of the input data,
so that created_person has a reference to the original array.

**Comment by mcdonnelldean** [comment]
@psnider This looks like a bug, thanks for reporting

@geek can you confirm?

@rjrodger I need access here too.

**Comment by geek** [comment]
I am not sure if that is the intended behavior or not, @rjrodger ?

The code is doing a lodash extend, which is an assignment of the enumerable properties of the `person` on the existing `person` object already in memory: https://github.com/rjrodger/seneca-mem-store/blob/master/mem-store.js#L75 https://lodash.com/docs#assign

**Comment by paolochiodi** [comment]
@geek @rjrodger do we have an answer here? I'm refactoring seneca-store-test and I'd like to merge @maxired PR or provide a similar test if this is considered a bug

**Comment by rjrodger** [comment]
this is definitly a bug - there should be no shared references

**Comment by mcdonnelldean** [comment]
@psnider This was indeed a bug, it is now resolved on master. I'll speak to @geek about getting a release out. Thanks for reporting :D

**Comment by geek** [comment]
@mcdonnelldean @rjrodger I don't have permission to publish a new version on npm :/

Please add `wyatt` if you want me to publish
