### ISSUE TITLE
scripts should not rely on globally installed tools

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-mem-store#25]
see seneca package.json usage of local lab, for example

**Comment by mcdonnelldean** [comment]
@rjrodger On this,

Do you mean use `node_modules/lab`. We are already forcing localness with:

```
  "devDependencies": {
    "docco": "0.7.0",
    "lab": "^6.2.0"
  }
```

The reason we changed it is the folks at npm have been telling people via twitter the correct way to call local dev dependencies is to put them in `dev dependencies`. NPM will correctly pick up the local version.

Let me see if I can find the tweets, they where from Isaac,  he said the other way caused issues.

**Comment by rjrodger** [comment]
yes

so cool if npm does this for us - you will need to verify though

**Comment by mcdonnelldean** [comment]
@rjrodger Yup, I have a tweet out to them and I will also get some docs around this on /contrib as it will cause confusion otherwise :D

**Comment by mcdonnelldean** [comment]
Confirmed https://github.com/npm/npm/issues/3883#issuecomment-31859121
