### ISSUE TITLE
copyright notices should use the same format as hapi

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-mem-store#26]
https://github.com/hapijs/hapi/blob/master/LICENSE

**Comment by mcdonnelldean** [comment]
@rjrodger should these be in all source files too? From speaking to some people at JSConfIt, they should. Thoughts?

**Comment by rjrodger** [comment]
yes all source files need a copyright header

**Comment by mcdonnelldean** [comment]
:+1:
