### ISSUE TITLE
our little quaintness with `else`

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-mem-store#29]
https://github.com/senecajs/seneca-mem-store/blob/master/mem-store.js#L56

**Comment by mcdonnelldean** [comment]
@rjrodger I've also done this for try...catch blocks as suggested by eslint (the engine for standard and lab) http://eslint.org/docs/rules/brace-style.html

**Comment by mcdonnelldean** [comment]
Fixed in #34
