### ISSUE TITLE
removing all entities from a mem store collections

### ISSUE THREAD

**Issue by akrsmv** [senecajs/seneca-mem-store#46]
I am searching for a way to purge my collections after each test completes. Looking in the code found this [all$](https://github.com/senecajs/seneca-mem-store/blob/master/mem-store.js#L207) property that by my guessing is having something with my problem but was unable to make use of it. What am I missing?

**Comment by mcdonnelldean** [comment]
@krassi-atanasov That's a good question. I'm not actually sure the correct way to do this. @mihaidma should be around tomorrow. I can ask him about it then 👍 He's our store Guru :D

**Comment by mihaidma** [comment]
@krassi-atanasov is this what you are looking for? https://github.com/senecajs/seneca-store-test/blob/master/store-test.js#L60
seneca-store-test ca be used as reference on how to use stores/entities

**Comment by akrsmv** [comment]
Yup, thanks. I ended up doing similar, initially I thought there might be some built in command, then I realized this is one of the trade-offs when one wants to build a db layer agnostic system.. (I am exploring seneca, and as much I am excited about it so are the number of questions I have  :-)) 
(Closing that one)
