### ISSUE TITLE
dependency on generate_id from seneca-basic

### ISSUE THREAD

**Issue by paolochiodi** [senecajs/seneca-mem-store#59]
This store uses the command `role:basic,cmd:generate_id` from seneca-basic to generate ids but doesn't require it, causing an error.

I had a brief discussion with @rjrodger on this and he was suggesting to move the id generation in seneca-entity so that this store (and other stores that depend on generate_id) always have it available.

**Comment by rjrodger** [comment]
seneca-entity now provides a generate_id method as an export
