### ISSUE TITLE
Objects should be cleaned with seneca.util.clean 

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-mem-store#78]
https://github.com/senecajs/seneca-mem-store/blob/0ebb4344cfd5cac4964185bccc2009a4d63f5d59/lib/common.ts#L15

**Comment by rjrodger** [comment]
interested to understand this issue
is the code used anymore?

**Comment by rjrodger** [comment]
is this issue still relevant

**Comment by lilsweetcaligula** [comment]
@rjrodger This issue may possibly be outdated by: https://github.com/senecajs/seneca-mem-store/blob/6db01cc75273fa44124dd698b03f188b92bc49bb/mem-store.ts#L102
