### ISSUE TITLE
use `null == foo` convention

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-mem-store#82]
https://github.com/senecajs/seneca-mem-store/blob/0ebb4344cfd5cac4964185bccc2009a4d63f5d59/mem-store.ts#L252

a) yoda style avoids incorrect assignment to null
b) == handles both null and undefined cases

**Comment by lilsweetcaligula** [comment]
@rjrodger 

> a) yoda style avoids incorrect assignment to null

That can be easily circumvented by placing null/undefined first:
```javascript
return ent && null === ent.id || typeof ent.id === 'undefined'
```

> b) == handles both null and undefined cases

The ==operator does automatic (implicit) conversion. I am not sure if the ==operator is a good alternative.

**Comment by rjrodger** [comment]
Noted. However this is Seneca code policy..
eslint yoda rule added to check this
