### ISSUE TITLE
serious performance issue

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-mem-store#84]
Some of the upsert tests are taking > 100ms. Compare to the existing tests where most take <5ms.
Since this is an in-memory store intended for fast tests, all tests need to be very fast.

NOTE: this is a blocking issue and must be fixed

**Comment by lilsweetcaligula** [comment]
This turned out to be not a problem with the mem-store code, but rather with the shared test suite code:
https://github.com/senecajs/seneca-store-test/pull/68

**Comment by rjrodger** [comment]
yeah makes sense!
