### ISSUE TITLE
test case when id$ = null

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-mem-store#90]
does this break things? given the `undefined ===` checks it might! let's find out

**Comment by lilsweetcaligula** [comment]
https://github.com/senecajs/seneca-store-test/pull/69

**Comment by rjrodger** [comment]
well? what broke? 
do we need to modify the undefined === checks?

**Comment by rjrodger** [comment]
is this done? I did not see it in the test code, but may have missed it

**Comment by lilsweetcaligula** [comment]
@rjrodger Yes, it's done. The test code may be found here:
https://github.com/senecajs/seneca-store-test/blob/master/store-test.js#L380
https://github.com/senecajs/seneca-store-test/pull/69 (merged)
