### ISSUE TITLE
Incorrect test coverage reported

### ISSUE THREAD

**Issue by lilsweetcaligula** [senecajs/seneca-mem-store#92]
When I extracted internal utilities into a separate file, I have run into the bug described in this question on StackOverflow:
https://stackoverflow.com/questions/60952924/hapi-lab-with-lab-transform-typescript-is-returning-buggy-code-coverage-results
dist/mem-store.js missing coverage from file(s):       
>  null on line(s): , , , , , , , , , , , , , , , , ,

https://github.com/hapijs/lab/issues/952
> This is not going to be fixed. Going to drop sourcemap support.

Additional resources:
https://github.com/hapijs/lab/issues/952#issuecomment-612118452

**Comment by rjrodger** [comment]
is this now resolved?

**Comment by lilsweetcaligula** [comment]
@rjrodger 
For now yes, but the problem will likely resurface somewhere down the line.
